// <auto-generated />
namespace Linkedin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class za : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(za));
        
        string IMigrationMetadata.Id
        {
            get { return "201903031615102_za"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
